table ParkAreas {
    id int [pk]     
    name varchar
    //Can have many guests 
    }

table Guests {
    id int [pk]
    name varchar
    area_id int [ref: > ParkAreas.id]
    //Can be in one park but not many
}

table Services {
    id int
    name varchar
}

table AreasServices {
    id int
    area_id int [ref: > ParkAreas.id]
    service_id int [ref: > Services.id]
}
